### ISSUE TITLE
oracle_grants: grants to roles are alternately granted and revoked on ansible runs

### ISSUE THREAD

**Issue by chrisbrookes** [oravirt/ansible-oracle-modules#80]
Given the playbook below, the roles that are listed for the grants are added the first time I run it. The next time they're removed. And the next, added again. 

I think there's some not-quite-right logic around computing/applying differences. I added some logging to the module and output the total_sql var just before it is executed and the first time it is:
```
DEBUG:__main__:total_sql: ['grant IMP_FULL_DATABASE,CONNECT to test_role']
```
Next time:
```
DEBUG:__main__:total_sql: ['grant IMP_FULL_DATABASE,CONNECT to test_role', 'revoke imp_full_database,connect from test_role']
```
The sql is executed in order so the revoke just wipes out the grant. Technically, the ansible task shouldn't run the second time since the grants are already applied.
 
Note that system privilege grants don't suffer from this problem, i.e. adding `- "CREATE TABLE"` to the list of grants works as expected when run multiple times.

## The playbook
```
#!/usr/bin/env ansible-playbook
---
- hosts: centosora1
  remote_user: root
  become: yes
  become_user: oracle

  vars:
    oracle_home: /u01/app/oracle/11.2.0.4/db1 # centosora1
    hostname: centosora1
    service_name: oradb
    user: sys
    password: 
    mode: sysdba
    oracle_env:
      ORACLE_HOME: "{{ oracle_home }}"
      LD_LIBRARY_PATH: "{{ oracle_home }}/lib"

    oracle_roles:
      - name: test_role
        state: present
        grants:
        - "CONNECT"
        - "IMP_FULL_DATABASE"
        object_privs:

  tasks:
    # this just creates the role, nothing wrong with this one.
    - name: Create role
      oracle_role:
        hostname: "{{ hostname }}"
        service_name: "{{ service_name }}"
        mode: "{{ mode }}"
        user: "{{ user }}"
        password: "{{ password }}"
        role: "{{ item.name }}"
      environment: "{{ oracle_env }}"
      with_items: "{{ oracle_roles }}"

    - name: Add grants to role
      oracle_grants:
        hostname: "{{ hostname }}"
        service_name: "{{ service_name }}"
        user: sys
        mode: sysdba
        password: "{{ password }}"
        role: "{{ item.name }}"
        grants: "{{ item.grants }}"
        object_privs: "{{ item.object_privs }}"
        state: "{{ item.state }}"
      environment: "{{ oracle_env }}"
      with_items:
        - "{{ oracle_roles }}"
```

**Comment by chrisbrookes** [comment]
Ahh, after looking at the log output again after submitting this, I see the roles are lower case. I specify them in upper case. If the roles are changed to lower case:

```
        grants:
        - "connect"
        - "imp_full_database"
```
Then the roles are not revoked in subsequent runs. The task is still seen as changed however.

**Comment by oravirt** [comment]
I’ll have a look

**Comment by oravirt** [comment]
Hi,
I've fixed the upper/lowercase problem with ab908effbbdc10720f5f84a42d1a3caa0fee7e39, but I could not reproduce your problem with the task always coming back as changed.

If there is nothing to do it just comes back green

**Comment by chrisbrookes** [comment]
Thanks for the case fix, confirmed this works.

As for the changed check, I still get yellow every time when I run the "Add grants to role" task in my example. Do you do anything in the modules that affect the changed state, or is this all internal Ansible? If the former I could do a bit of debugging...

**Comment by chrisbrookes** [comment]
Doesn't matter, I've found the changed var that comes back from modulel.exit_json.

**Comment by chrisbrookes** [comment]
The problem is with [this line](https://github.com/oravirt/ansible-oracle-modules/blob/ab908effbbdc10720f5f84a42d1a3caa0fee7e39/oracle_grants#L341): 
```
if not any(x in exceptions_list for x in wanted_grants_list_upper):
```
Exceptions_list has CONNECT in, and I have that role as one of my grants along with other sys priv grants. If I take CONNECT out of the list, then it works as expected. The if statement means my other sys priv grants are not added to total_current. Consequently the actual grants for these are applied every time and changed will always be true.

I think that check for roles in the _wanted_grants_list_upper_ list should instead perhaps just remove any roles in there but keep the other sys grants?

**Comment by oravirt** [comment]
Ok that’s weird. I used your example when I debugged this and that worked as expected.
Is that example the full example (including all other grants)?
If not, could you maybe give me a Gist or an inline example that reproduces the problem?
Which ansible version are you using?

**Comment by chrisbrookes** [comment]
ansible 2.7.1.
Ah my grants are different to above example (which works ok), replace the oracle_roles with the following grants and you should get the problem:
```
    oracle_roles:
      - name: test_role
        state: present
        grants:
        - "CONNECT"
        - "create database link"
        - "create procedure"
        - "create sequence"
        - "create synonym"
        - "create table"
        - "create trigger"
        - "create type"
        - "create view"
        object_privs:
```

**Comment by oravirt** [comment]
https://github.com/oravirt/ansible-oracle-modules/commit/b3066dff24523a5e66c619e10821a18e9f218ccf should fix this.

The reason I added the exceptions list in the first place was for the reason described in the commit. A quick and dirty fix at the time, hopefully a bit more refined this time ;-)

**Comment by chrisbrookes** [comment]
Tested and confirmed it works, thanks very much!
